/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_forkbomb_NativeLib */

#ifndef _Included_com_example_forkbomb_NativeLib
#define _Included_com_example_forkbomb_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_forkbomb_NativeLib
 * Method:    fb
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_forkbomb_NativeLib_fb
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
